### ISSUE TITLE
Add automatic testing on windows platform using AppVeyor

### ISSUE THREAD

**Issue by amjith** [dbcli/pgcli#114]
Check if it's possible to use http://www.appveyor.com/ for testing on Windows.

**Comment by amjith** [comment]
It is high time we do this. I don't want new features to silently break in Windows. 

@dbcli/pgcli-core Any takers? If I don't hear back by Friday, I'll start investigating how to add this.

**Comment by j-bennet** [comment]
I'm interested. Let me look into this.

**Comment by j-bennet** [comment]
I played with this for wharfee and found that pexpect is not available on Windows. In fact, it's available there starting with version 4, but we're pinning it to 3.3 because 4.0 can't run under python 2.6 (see #375).

I think I'll add the config to run unit tests without functional (behave) tests to start with, and then look for ways to replace (or upgrade) pexpect and run functional tests.

**Comment by darikg** [comment]
Would it be possible to do linux tests with pexpect=3.3 and windows tests with pexpect=4? The number of windows python 2.6 users has to be pretty small and it might not be worth worrying about.

**Comment by j-bennet** [comment]
@darikg So only test under 2.7, 3.3 and 3.4 on Windows? That may be an option.

**Comment by darikg** [comment]
Yeah, exactly

**Comment by amjith** [comment]
I like this suggestion. :)

**Comment by j-bennet** [comment]
https://ci.appveyor.com/project/j-bennet/pgcli/build/job/qdqvwl9hpexmrcbp

Hmm... it fails trying to install psycopg2 on Win? What the...

**Comment by amjith** [comment]
Interestingly, that's what I expected. It's not easy to install psycopg on
windows using pip.

I had to download an exe file and use easy install to install it.

**Comment by darikg** [comment]
@j-bennet I played around with your appveyor.yml and got this to install psycopg2 and run the tests. You can see it downloads psycopg2 pre-compiled binaries [from here](http://www.stickpeople.com/projects/python/win-psycopg/). The problem is I had to hardcode the path to a specific python/arch, so I'm not sure go to get that to work with the environmental matrix. 

```
build: false

services:
  - postgresql

environment:
  matrix:
    - PYTHON: "C:\\Python34"
      PYTHON_VERSION: "3.4.1"
      PYTHON_ARCH: "32"

init:
  - "PATH=C:\\Program Files\\PostgreSQL\\9.3\\bin\\;%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "SET PGUSER=postgres"
  - "SET PGPASSWORD=Password12!"
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - ps: (new-object net.webclient).DownloadFile('http://www.stickpeople.com/projects/python/win-psycopg/2.6.1/psycopg2-2.6.1.win32-py3.4-pg9.4.4-release.exe', 'C:/psycopg.exe')
  - "easy_install c:/psycopg.exe"
  - "pip install -r requirements-win.txt"
  - "pip install ."

test_script:
  - "py.test"
  - "cd tests" 
  - "behave"
```
